
spring:
  application:
    name: distribute-demo
  redis:
    host: 192.168.0.129
    port: 6379
    database: 0
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        min-idle: 0
        max-idle: 8
  rabbitmq:
    host: 192.168.0.129
    port: 5672
    username: admin
    password: 123456
    virtual-host: lizhe
    publisher-confirm-type: correlated
    listener:
      direct:
        acknowledge-mode: manual


mybatis:
  mapper-locations: classpath:/mapper/*.xml
server:
  port: 8082



